### ISSUE TITLE
Spurious closing of sql conn!

### ISSUE THREAD

**Issue by mcsherrylabs** [mcsherrylabs/sss.asado#7]
8fcad
[INFO] [08/09/2016 21:54:47.826] [asado-network-node-akka.actor.default-dispatcher-22] [akka://asado-network-node/user/$f] Client syncing - committed block height 4326, num txs  102
[ERROR] [08/09/2016 21:54:47.834] [asado-network-node-akka.actor.default-dispatcher-23] [akka://asado-network-node/user/$a] connection exception: closed
java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCBlobClient.getBytes(Unknown Source)
	at sss.db.package$Row.blobToBytes(package.scala:74)
	at sss.db.package$Row.apply(package.scala:65)
	at sss.asado.wallet.WalletPersistence$$anonfun$listUnSpent$1.apply(WalletPersistence.scala:65)
	at sss.asado.wallet.WalletPersistence$$anonfun$listUnSpent$1.apply(WalletPersistence.scala:65)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sss.asado.wallet.WalletPersistence.listUnSpent(WalletPersistence.scala:65)
	at sss.asado.wallet.Wallet.findUnSpent(Wallet.scala:172)
	at sss.asado.wallet.Wallet.createTx(Wallet.scala:73)
	at sss.asado.wallet.IntegratedWallet.pay(IntegratedWallet.scala:150)
	at messagesender.OrchestratingActor$$anonfun$receive$1$$anonfun$applyOrElse$1$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(OrchestratingActor.scala:65)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at messagesender.OrchestratingActor$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcVI$sp(OrchestratingActor.scala:64)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at messagesender.OrchestratingActor$$anonfun$receive$1.applyOrElse(OrchestratingActor.scala:63)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at messagesender.OrchestratingActor.aroundReceive(OrchestratingActor.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.types.BlobDataID.getBytes(Unknown Source)
	... 33 more

**Comment by mcsherrylabs** [comment]
A BLOB in a row accessed via r[Array[Byte]]("blob_col_name") is guaranteed valid only as long as the transaction is open! (http://hsqldb.org/doc/apidocs/org/hsqldb/jdbc/JDBCBlob.html)

All reading of Blobs into Arrays must be done in a tx.
