### ISSUE TITLE
Sql conn closed.

### ISSUE THREAD

**Issue by mcsherrylabs** [mcsherrylabs/sss.asado#8]
0848832989 eve, defaultTag, 479BD8A1167C623801EF36841E373D4ECB0D6905B003ABED1EFD86607DAEF91AB0EFBF42F48C928967CBFB50B1DB7F122D3E51760DF806AED19C6DD7DBE1C881
[asado-network-node-akka.actor.default-dispatcher-5] >> [INFO ] sss.asado.ServicesMain$$anon$1 >> 09:57:36.248 Attempting to verify testsender9697, defaultTag 
[asado-network-node-akka.actor.default-dispatcher-5] >> [INFO ] sss.asado.ServicesMain$$anon$1 >> 09:57:36.248 msg -3477312873363662048 pk Some(872BD80CACA17E468A92BD082EBC584891D587F583E37F813861AD6970593939)
[asado-network-node-akka.actor.default-dispatcher-5] >> [INFO ] sss.asado.ServicesMain$$anon$1 >> 09:57:36.248 sig BC579F8DF9C03ABBAF0286E156635578C31E38C918E3A29459BA4D0535EE8F021F522849BDFE3C3DA24EA07F81C0022E7AFDDF5E7E75FB04CE19D7B7F431BD86 
[asado-network-node-akka.actor.default-dispatcher-5] >> [INFO ] sss.asado.ServicesMain$$anon$1 >> 09:57:36.249 testsender9697, defaultTag verified using identity ledger
[asado-network-node-akka.actor.default-dispatcher-5] >> [WARN ] s.a.state.AsadoCoreStateMachineActor >> 09:57:36.249 Event(ConnectionGained(Connection(NodeId(testsender9697,/127.0.0.1:39450),Actor[akka://asado-network-node/user/$c/$f#-1169067124]),Set(Connection(NodeId(testsender9698,/127.0.0.1:39446),Actor[akka://asado-network-node/user/$c/$e#1657292634]), Connection(NodeId(testsender9697,/127.0.0.1:39450),Actor[akka://asado-network-node/user/$c/$f#-1169067124]))),Some(bob))
[asado-network-node-akka.actor.default-dispatcher-8] >> [INFO ] sss.asado.block.SimpleTxPageActor >> 09:57:36.346 Actor[akka://asado-network-node/user/$c/$f#-1169067124] asking me for GetTxPage(4711,0,50)
[asado-network-node-akka.actor.default-dispatcher-2] >> [INFO ] sss.asado.block.SimpleTxPageActor >> 09:57:39.781 Actor[akka://asado-network-node/user/$c/$f#-1169067124] asking me for GetTxPage(4711,50,50)
[asado-network-node-akka.actor.default-dispatcher-29] >> [ERROR] akka.actor.OneForOneStrategy >> 09:57:41.979 connection exception: closed
java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[org.hsqldb.hsqldb-2.3.4.jar:2.3.4]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[org.hsqldb.hsqldb-2.3.4.jar:2.3.4]
	at org.hsqldb.jdbc.JDBCBlobClient.getBytes(Unknown Source) ~[org.hsqldb.hsqldb-2.3.4.jar:2.3.4]
	at sss.db.package$Row.blobToBytes(package.scala:74) ~[mcsherrylabs.com.sss-db_2.11-0.9.31.jar:0.9.31]
	at sss.db.package$Row.apply(package.scala:65) ~[mcsherrylabs.com.sss-db_2.11-0.9.31.jar:0.9.31]
	at sss.asado.block.Block$$anonfun$page$1.apply(Block.scala:73) ~[mcsherrylabs.com.sss-asado-node-0.2.11-SNAPSHOT.jar:0.2.11-SNAPSHOT]
	at sss.asado.block.Block$$anonfun$page$1.apply(Block.scala:70) ~[mcsherrylabs.com.sss-asado-node-0.2.11-SNAPSHOT.jar:0.2.11-SNAPSHOT]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at sss.asado.block.Block.page(Block.scala:70) ~[mcsherrylabs.com.sss-asado-node-0.2.11-SNAPSHOT.jar:0.2.11-SNAPSHOT]
	at sss.asado.block.SimpleTxPageActor$$anonfun$receive$1.nextPage$lzycompute$1(SimpleTxPageActor.scala:48) ~[mcsherrylabs.com.sss-asado-node-0.2.11-SNAPSHOT.jar:0.2.11-SNAPSHOT]
	at sss.asado.block.SimpleTxPageActor$$anonfun$receive$1.sss$asado$block$SimpleTxPageActor$$anonfun$$nextPage$1(SimpleTxPageActor.scala:48) ~[mcsherrylabs.com.sss-asado-node-0.2.11-SNAPSHOT.jar:0.2.11-SNAPSHOT]
	at sss.asado.block.SimpleTxPageActor$$anonfun$receive$1.applyOrElse(SimpleTxPageActor.scala:52) ~[mcsherrylabs.com.sss-asado-node-0.2.11-SNAPSHOT.jar:0.2.11-SNAPSHOT]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[com.typesafe.akka.akka-actor_2.11-2.4.9-RC2.jar:na]
	at sss.asado.block.SimpleTxPageActor.aroundReceive(SimpleTxPageActor.scala:22) ~[mcsherrylabs.com.sss-asado-node-0.2.11-SNAPSHOT.jar:0.2.11-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [com.typesafe.akka.akka-actor_2.11-2.4.9-RC2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [com.typesafe.akka.akka-actor_2.11-2.4.9-RC2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [com.typesafe.akka.akka-actor_2.11-2.4.9-RC2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.9-RC2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.9-RC2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.8.jar:na]
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source) ~[org.hsqldb.hsqldb-2.3.4.jar:2.3.4]
	at org.hsqldb.types.BlobDataID.getBytes(Unknown Source) ~[org.hsqldb.hsqldb-2.3.4.jar:2.3.4]
	... 28 common frames omitted
[asado-network-node-akka.actor.default-dispatcher-29] >> [INFO ] sss.asado.block.SimpleTxPageActor >> 09:57:41.979 Simple TxPage actor has started...
[asado-network-node-akka.actor.default-dispatcher-5] >> [INFO ] sss.asado.block.SimpleTxPageActor >> 09:57:52.948 Actor[akka://asado-network-node/user/$c/$e#1657292634] asking me for GetTxPage(4711,832,50)
[asado-network-node-akka.actor.default-dispatcher-22] >> [INFO ] sss.asado.block.SimpleTxPageActor >> 09:58:12.979 Actor[akka://asado-network-node/user/$c/$e#1657292634] asking me for GetTxPage(4711,832,50)

**Comment by mcsherrylabs** [comment]
See #7 , same problem.
